### ISSUE TITLE
[BUG]Doesn't build with espressif 6.12.0, 6.13.0 or 7.0.0 using platform.io

### ISSUE THREAD

**Issue by benpeart** [mathieucarbou/MycilaESPConnect#58]
**Firmware**

[env]
platform = espressif32@7.0.0
board = esp32dev
framework = arduino

**Description**

The library doesn't build with 6.12.0, 6.13.0 or 7.0.0. Initial errors are:

In file included from .pio/libdeps/debug/MycilaESPConnect/src/MycilaESPConnect.cpp:6:
.pio/libdeps/debug/MycilaESPConnect/src/MycilaESPConnect_Includes.h:22:12: fatal error: MacAddress.h: No such file or directory

If I update MycilaESPConnect\src\MycilaESPConnect_Includes.h so that the ESP32   #include <./backport/MacAddress.h> like is done for the ESP8266 I get a bunch more errors that makes me think that something has changed in the ESP32 WiFi stack APIs. I tried 3 different versions of espressif libraries trying to find one that works but haven't found one that builds successfully.

.pio/libdeps/debug/MycilaESPConnect/src/MycilaESPConnect.cpp: In member function 'Mycila::ESPConnect::Mode Mycila::ESPConnect::getMode() const':
.pio/libdeps/debug/MycilaESPConnect/src/MycilaESPConnect.cpp:53:16: error: 'class WiFiClass' has no member named 'STA'
       if (WiFi.STA.hasIP())
                ^~~
.pio/libdeps/debug/MycilaESPConnect/src/MycilaESPConnect.cpp: In member function 'IPAddress Mycila::ESPConnect::getLinkLocalIPv6Address(Mycila::ESPConnect::Mode) const':
.pio/libdeps/debug/MycilaESPConnect/src/MycilaESPConnect.cpp:149:14: error: 'IN6ADDR_ANY' was not declared in this scope
       return IN6ADDR_ANY;
              ^~~~~~~~~~~
.pio/libdeps/debug/MycilaESPConnect/src/MycilaESPConnect_STA.cpp: In member function 'void Mycila::ESPConnect::_startSTA()':
.pio/libdeps/debug/MycilaESPConnect/src/MycilaESPConnect_STA.cpp:28:8: error: 'class WiFiClass' has no member named 'enableIPv6'; did you mean 'enableIpV6'?
   WiFi.enableIPv6();
        ^~~~~~~~~~
        enableIpV6
.pio/libdeps/debug/MycilaESPConnect/src/MycilaESPConnect_STA.cpp:46:5: error: 'MacAddress' was not declared in this scope
     MacAddress bssid(MACType::MAC6);
     ^~~~~~~~~~
.pio/libdeps/debug/MycilaESPConnect/src/MycilaESPConnect_STA.cpp:46:5: note: suggested alternative: 'IPAddress'
     MacAddress bssid(MACType::MAC6);
     ^~~~~~~~~~
     IPAddress
.pio/libdeps/debug/MycilaESPConnect/src/MycilaESPConnect_STA.cpp:47:5: error: 'bssid' was not declared in this scope
     bssid.fromString(_config.wifiBSSID.c_str());
     ^~~~~
.pio/libdeps/debug/MycilaESPConnect/src/MycilaESPConnect.cpp:149:14: note: suggested alternative: 'IP6_ADDR_ANY'
       return IN6ADDR_ANY;
              ^~~~~~~~~~~
              IP6_ADDR_ANY
.pio/libdeps/debug/MycilaESPConnect/src/MycilaESPConnect.cpp:151:47: error: 'class WiFiClass' has no member named 'linkLocalIPv6'; did you mean 'localIPv6'?
       return wifiMode == WIFI_MODE_STA ? WiFi.linkLocalIPv6() : IN6ADDR_ANY;
                                               ^~~~~~~~~~~~~
                                               localIPv6
.pio/libdeps/debug/MycilaESPConnect/src/MycilaESPConnect.cpp: In member function 'IPAddress Mycila::ESPConnect::getGlobalIPv6Address(Mycila::ESPConnect::Mode) const':
.pio/libdeps/debug/MycilaESPConnect/src/MycilaESPConnect.cpp:169:14: error: 'IN6ADDR_ANY' was not declared in this scope
       return IN6ADDR_ANY;
              ^~~~~~~~~~~
.pio/libdeps/debug/MycilaESPConnect/src/MycilaESPConnect_STA.cpp:47:5: note: suggested alternative: 'setsid'
     bssid.fromString(_config.wifiBSSID.c_str());
     ^~~~~
     setsid
.pio/libdeps/debug/MycilaESPConnect/src/MycilaESPConnect.cpp:169:14: note: suggested alternative: 'IP6_ADDR_ANY'
       return IN6ADDR_ANY;
              ^~~~~~~~~~~
              IP6_ADDR_ANY
.pio/libdeps/debug/MycilaESPConnect/src/MycilaESPConnect.cpp:171:47: error: 'class WiFiClass' has no member named 'globalIPv6'; did you mean 'localIPv6'?
       return wifiMode == WIFI_MODE_STA ? WiFi.globalIPv6() : IN6ADDR_ANY;
                                               ^~~~~~~~~~
                                               localIPv6
.pio/libdeps/debug/MycilaESPConnect/src/MycilaESPConnect_CP.cpp: In member function 'void Mycila::ESPConnect::_startCredentialTest()':
.pio/libdeps/debug/MycilaESPConnect/src/MycilaESPConnect_CP.cpp:254:7: error: 'MacAddress' was not declared in this scope
       MacAddress bssid(MACType::MAC6);
       ^~~~~~~~~~
.pio/libdeps/debug/MycilaESPConnect/src/MycilaESPConnect_Lifecycle.cpp: In member function 'void Mycila::ESPConnect::_onWiFiEvent(arduino_event_id_t)':
.pio/libdeps/debug/MycilaESPConnect/src/MycilaESPConnect_Lifecycle.cpp:280:16: error: 'class WiFiClass' has no member named 'linkLocalIPv6'; did you mean 'localIPv6'?
       if (WiFi.linkLocalIPv6() != IN6ADDR_ANY) {
                ^~~~~~~~~~~~~
                localIPv6
.pio/libdeps/debug/MycilaESPConnect/src/MycilaESPConnect_Lifecycle.cpp:280:35: error: 'IN6ADDR_ANY' was not declared in this scope
       if (WiFi.linkLocalIPv6() != IN6ADDR_ANY) {
                                   ^~~~~~~~~~~
.pio/libdeps/debug/MycilaESPConnect/src/MycilaESPConnect_CP.cpp:254:7: note: suggested alternative: 'IPAddress'
       MacAddress bssid(MACType::MAC6);
       ^~~~~~~~~~
       IPAddress
.pio/libdeps/debug/MycilaESPConnect/src/MycilaESPConnect_CP.cpp:255:7: error: 'bssid' was not declared in this scope
       bssid.fromString(underTest->wifiBSSID.c_str());
       ^~~~~
.pio/libdeps/debug/MycilaESPConnect/src/MycilaESPConnect_Lifecycle.cpp:280:35: note: suggested alternative: 'IP6_ADDR_ANY'
       if (WiFi.linkLocalIPv6() != IN6ADDR_ANY) {
                                   ^~~~~~~~~~~
                                   IP6_ADDR_ANY
.pio/libdeps/debug/MycilaESPConnect/src/MycilaESPConnect_Lifecycle.cpp:281:18: error: 'class WiFiClass' has no member named 'globalIPv6'; did you mean 'localIPv6'?
         if (WiFi.globalIPv6() == IN6ADDR_ANY) {
                  ^~~~~~~~~~
                  localIPv6
.pio/libdeps/debug/MycilaESPConnect/src/MycilaESPConnect_CP.cpp:255:7: note: suggested alternative: 'setsid'
       bssid.fromString(underTest->wifiBSSID.c_str());
       ^~~~~
       setsid

**Board**

esp32dev

**Ethernet adapter used ?**

NA

**Stack trace**

NA

**Additional notes**

NA

**Screenshots**

NA

**Comment by mathieucarbou** [comment]
@benpeart that's not a bug. You MUST NOT use platforms from platformio since they dropped support for Arduino.

Use instead pioarduino: https://github.com/mathieucarbou/MycilaESPConnect#platformio
